google-analytics:
  id: 'UA-37952868-1'

google-adwords:
  id: '956542766'
  mappings:
    - evt: 'success:onboarding'
      label: 'AkwwCNLEnGUQrt6OyAM'
    - evt: 'success:signup'
      label: '77nYCOS34F4Qrt6OyAM'

facebook-pixel:
  id: '417778941754366'

twitter-ads-pixel:
  id: 'nus5f'
  mappings:
    - evt: 'success:pricing-checkout'
      pid: 'l6ljz'
    - evt: 'success:signup'
      pid: 'l6liv'
